### ISSUE TITLE
Research: mLab

### ISSUE THREAD

**Issue by rossjs** [PerfectPizza/OpenInvite#8]
Research regarding mLab, the MongoDB online database site.

**Comment by GMDIV** [comment]
Sandbox
Our free Sandbox plan provides a single database with 0.5 GB of storage on a shared database server process running on a shared virtual machine (VM). This plan is best for development and prototyping.
PLAN HIGHLIGHTS
No expiration
Expert database support
Data browser
Free system-level backups
Free and easy restores of custom backups
Continuous monitoring, 24x7
RAM
Variable 
Storage
0.5 GB 
Monthly Price
FREE

**Comment by GMDIV** [comment]
https://mlab.com/signup/

**Comment by GMDIV** [comment]
https://mlab.com/plans/pricing/

**Comment by GMDIV** [comment]
https://elements.heroku.com/addons/mongolab

**Comment by GMDIV** [comment]
Abilities of heroku with github:
 Connect to GitHub
Connect this app to GitHub to enable code diffs and deploys.
View your code diffs on GitHub

Connect your app to a GitHub repository to see commit diffs in the activity log.

Deploy changes with GitHub

Connecting to a repository will allow you to deploy a branch to your app.

Automatic deploys from GitHub

Select a branch to deploy automatically whenever it is pushed to.

Create review apps in pipelines

Pipelines connected to GitHub can enable review apps, and create apps for new pull requests. Learn more.

Connect to GitHub
