### ISSUE TITLE
Research: Facebook API

### ISSUE THREAD

**Issue by rossjs** [PerfectPizza/OpenInvite#9]
Research stuff for the Facebook API implementation.

**Comment by rtopol2** [comment]
asdasdasd as

**Comment by rossjs** [comment]
Facebook Login guide: https://developers.facebook.com/docs/facebook-login/web

**Comment by rossjs** [comment]
Access Friends List: https://developers.facebook.com/docs/graph-api/reference/friend-list/

**Comment by rossjs** [comment]
actually, I think this is what we need: https://developers.facebook.com/docs/graph-api/reference/user/friends/

**Comment by AriLFrankel** [comment]
have to use a live site. Currently using this URL: http://arileofrankel.com/static/facebookAuthPage2.html

Login gives back a token that can be used to GET. This is a link to show what we can do with that: https://developers.facebook.com/tools/explorer?method=GET&path=me%3Ffields%3Did%2Cname%2Cfriends%2Cpicture&version=v2.8
